# _config.yml  (PROJECT SITE)

title: "Kelvin Ervais — Data Science & Analytics"
description: "R & Python, ML modeling, Shiny dashboards, and data storytelling."
theme: minima

author:
  name: Kelvin Ervais
  email: kelvinervais@gmail.com

minima:
  social_links:
    - { platform: github,   user_url: "https://github.com/kelvinervais" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/kelvinervais/" }

url: "https://kelvinervais.github.io"
baseurl: "/website"   # <-- REQUIRED for repo named 'website'

plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: page
